/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddFriendModal: typeof import('./components/AddFriendModal/index.vue')['default']
    Avatar: typeof import('./components/Avatar/index.vue')['default']
    CreateGroupModal: typeof import('./components/CreateGroupModal/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    Emoji: typeof import('./components/RenderMessage/emoji.vue')['default']
    File: typeof import('./components/RenderMessage/file.vue')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    IEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    IEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpFemale: typeof import('~icons/ep/female')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMale: typeof import('~icons/ep/male')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    Image: typeof import('./components/RenderMessage/image.vue')['default']
    LoginBox: typeof import('./components/LoginBox/index.vue')['default']
    MsgReadModal: typeof import('./components/MsgReadModal/index.vue')['default']
    RenderMessage: typeof import('./components/RenderMessage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectUser: typeof import('./components/CreateGroupModal/SelectUser.vue')['default']
    Text: typeof import('./components/RenderMessage/text.vue')['default']
    UserItem: typeof import('./components/MsgReadModal/UserItem.vue')['default']
    UserSettingBox: typeof import('./components/UserSettingBox/index.vue')['default']
    Video: typeof import('./components/RenderMessage/video.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer/index.vue')['default']
    Voice: typeof import('./components/RenderMessage/voice.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
