/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/avatar/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    File: typeof import('./components/RenderMessage/file.vue')['default']
    Icon: typeof import('./components/Icon/index.vue')['default']
    IEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    IEpChatDotRound: typeof import('~icons/ep/chat-dot-round')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpFemale: typeof import('~icons/ep/female')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMale: typeof import('~icons/ep/male')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    Image: typeof import('./components/RenderMessage/image.vue')['default']
    LoginBox: typeof import('./components/LoginBox/index.vue')['default']
    RenderMessage: typeof import('./components/RenderMessage/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./components/RenderMessage/text.vue')['default']
    UserSettingBox: typeof import('./components/UserSettingBox/index.vue')['default']
    Video: typeof import('./components/RenderMessage/video.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer/index.vue')['default']
    Voice: typeof import('./components/RenderMessage/voice.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
